### PR TITLE
Added json output function

### PR DESCRIPTION
**Pull request by fksms**
I added it because I needed the ability to output it as json.

`dust -j` outputs json to the current directory.

For your reference.

### CODE REVIEW

**Comment by bootandy** [comment]
Ok, lets fix the format and go

**Comment by fksms** [comment]
Thank you for confirmation.

What specifically should I fix?

**Comment by bootandy** [comment]
Run `cargo fmt` locally - you can see the build failed above ^ , then push again.

**Comment by bootandy** [comment]
and rebase

**Comment by fksms** [comment]
Very helpful.

I've Done!

**Comment by bootandy** [comment]
https://github.com/bootandy/dust/pull/396
Here, we print to stdout instead - I don't want my tool writing files to the disk. - if you want the old behaviour you can do 
`dust > node.json`

**Pull request merged**
