### PR TITLE
eprint problematic folders

### PR DESCRIPTION
**Pull request by Its-Just-Nans**
This PR change the `Did not have permissions..` message to print problematic folders/files

Why this PR: I think it's useful to have the list of the problematic folders/files

### CODE REVIEW

**Comment by bootandy** [comment]
I don't want to do this - the list would be too long and obscure the 'real' output.

**Comment by Its-Just-Nans** [comment]
@bootandy what about adding a CLI flag to have the list?

I think the user would like to know where dust isn't working and check why it isn't !

**Comment by bootandy** [comment]
Ok, I'll accept it if we add a CLI flag to control it.

**Comment by Its-Just-Nans** [comment]
Thanks

I've added the flag

**Pull request merged**
