### PR TITLE
#321: display the size of a file or directory in "kilobytes"

### PR DESCRIPTION
**Pull request by TYzzt**
added **-k** parameter to display the size of a file or directory in "kilobytes"

### CODE REVIEW

**Comment by TYzzt** [comment]
hi, @bootandy, could you please help me review the code

**Comment by bootandy** [comment]
your code looks good.

**Comment by bootandy** [comment]
I think the code you have written is sensible. But I'm just not sure that we need to cover this usecase.

**Comment by TYzzt** [comment]
> 

thank you~ The kilobyte formatting is very useful in scenarios where higher precision is required. This is also the requirement that my work encounters.

**Comment by keenahn** [comment]
I would also like this, as well as bytes (aka the non human-readable version of `du`). I'll fork @TYzzt's branch :).

**Comment by bootandy** [comment]
https://github.com/bootandy/dust/pull/372

Commits from this PR moved to the above PR

**Pull request closed without merging**
