### PR TITLE
Adding -T flag for specifing thread usage.

### PR DESCRIPTION
**Pull request by Dj-Codeman**
This adds a cli flag:`-T, --threads` to allow limiting the number of threads that rayon uses while building the thread pool. I'm aware of being able to set rayon_thread_whatever = X but I believe this is a bit simpler.

### CODE REVIEW

**Comment by bootandy** [comment]
Ok, lets fix the formatting, and we'll add this

**Comment by bootandy** [comment]
Can you rebase and regenerate `completions/_dust` there seems to be a conflict - thanks.

**Comment by bootandy** [comment]
I apologise, but I merged another branch first and we need to regenerate can you rebase again. thanks.

**Comment by Dj-Codeman** [comment]
@bootandy Pretty sure I'm not doing something right. Missing what exactly it is, My understanding is 1. get newest changes from master 2. regenerate the completion with the new files that were pulled? It's late so I could just be dense

**Comment by bootandy** [comment]
Ok so we are in the unfortunate position that there were lots of other PRs that added command line flags. Everytime someone adds a command line flag it screws up the PR of everyone else - because completions/_dust is regenerated in a completely incompatible way. 

So we can either:
1) I squashed all your commits here and we can use this:
https://github.com/bootandy/dust/pull/395

2) or if you'd like we can keep trying with this PR. 
I find the easiest way is to squash your commits down. (git rebase -i HEAD^^^^^      ). Then I go to master, pull master and cherry-pick the squashed commit on to the new branch, run cargo build, commit --amend whatever it changes then push again.

**Comment by bootandy** [comment]
we'll use the other branch - thanks 
https://github.com/bootandy/dust/pull/395

**Pull request closed without merging**
