### PR TITLE
Support for completions

### PR DESCRIPTION
**Pull request by Jedsek**
Again :)

### CODE REVIEW

**Comment by Jedsek** [comment]
I help you reduce clap's feature, because `crate_version!` is just a simple macro:

```rust
#[cfg(feature = "cargo")]
#[macro_export]
macro_rules! crate_version {
    () => {
        env!("CARGO_PKG_VERSION")
    };
}
```

Just replace it by using `env!`

**Comment by Jedsek** [comment]
And now, no clippy warnings :)

**Comment by Jedsek** [comment]
Also, I changed the `edition` form `2018` to `2021` in `Cargo.toml` and it could be compiled successfully.

**Comment by bootandy** [comment]
Looks like the old 32 bit builds are broken.  (i686)  ( Could this be the change from 2018-> 2021 ? )

**Comment by Jedsek** [comment]
Oh, maybe a place that I changed.

**Comment by bootandy** [comment]
I don't think its the edition change as I opened a separate PR for that: https://github.com/bootandy/dust/pull/249

**Comment by Jedsek** [comment]
I fix the max depth.
(I just thought about 64 bit before)

**Comment by Jedsek** [comment]
Because a proble of clap, we could't set the default value of depth (When use a function which return value is a `Command`, because lifetime, see https://github.com/clap-rs/clap/issues/2150)

So I changed the `build_cli`'s signature to accept a new argument: `max_depth` to avold this problem. Otherwise, I think I have to add a dependencies `const_format` to achieve the same purpose.

**Comment by Jedsek** [comment]
@bootandy All checks have passed, this pr could be merged

**Pull request merged**
