### PR TITLE
Add support for completion

### PR DESCRIPTION
**Pull request by Jedsek**
See title.

### CODE REVIEW

**Comment by Jedsek** [comment]
I reduce `main` function, add new mod `cli` and build script.

**Comment by bootandy** [comment]
Yes, I'm quite happy for this to go in. I think pulling out the CLI options from the main script was a good refactor. 

I've just merged a change including a Cargo update. If you want to rebase then I'll accept.

**Comment by Jedsek** [comment]
oh...I had delete my fork....

**Comment by Jedsek** [comment]
Just again, little code :)

**Pull request closed without merging**
